-- Checkpoint audit values are observations, not defaults.  A missing runtime
-- result must remain NULL so it cannot be mistaken for an observed zero.
ALTER TABLE checkpoint_dispatch_audits
  ALTER COLUMN supported_cases_evaluated DROP NOT NULL,
  ALTER COLUMN supported_cases_evaluated DROP DEFAULT,
  ALTER COLUMN kho_ton_evaluated DROP NOT NULL,
  ALTER COLUMN kho_ton_evaluated DROP DEFAULT,
  ALTER COLUMN kho_chua_luan_chuyen_evaluated DROP NOT NULL,
  ALTER COLUMN kho_chua_luan_chuyen_evaluated DROP DEFAULT,
  ALTER COLUMN first_push_pending_created DROP NOT NULL,
  ALTER COLUMN first_push_pending_created DROP DEFAULT,
  ALTER COLUMN second_push_pending_created DROP NOT NULL,
  ALTER COLUMN second_push_pending_created DROP DEFAULT,
  ALTER COLUMN third_push_pending_created DROP NOT NULL,
  ALTER COLUMN third_push_pending_created DROP DEFAULT,
  ALTER COLUMN escalation_pending_created DROP NOT NULL,
  ALTER COLUMN escalation_pending_created DROP DEFAULT,
  ALTER COLUMN total_dispatch_eligible_pending DROP NOT NULL,
  ALTER COLUMN total_dispatch_eligible_pending DROP DEFAULT,
  ALTER COLUMN telegram_scanned DROP NOT NULL,
  ALTER COLUMN telegram_scanned DROP DEFAULT,
  ALTER COLUMN recipients_resolved DROP NOT NULL,
  ALTER COLUMN recipients_resolved DROP DEFAULT,
  ALTER COLUMN interactions_created DROP NOT NULL,
  ALTER COLUMN interactions_created DROP DEFAULT,
  ALTER COLUMN send_attempts DROP NOT NULL,
  ALTER COLUMN send_attempts DROP DEFAULT,
  ALTER COLUMN send_success DROP NOT NULL,
  ALTER COLUMN send_success DROP DEFAULT,
  ALTER COLUMN send_failed DROP NOT NULL,
  ALTER COLUMN send_failed DROP DEFAULT,
  ADD COLUMN IF NOT EXISTS status_updates_active INTEGER NULL,
  ADD COLUMN IF NOT EXISTS status_updates_resolved INTEGER NULL,
  ADD COLUMN IF NOT EXISTS status_update_batches_sent INTEGER NULL,
  ADD COLUMN IF NOT EXISTS status_update_batches_failed INTEGER NULL;
