"use client";

import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Save, Send, UsersRound } from "lucide-react";

type Group = { id: string; telegram_chat_id: string; title: string; status: string; created_at: string };
type Member = { id: string; group_id: string; telegram_user_id: string; display_name: string; username: string | null; warehouse_name: string | null; pilot_role: "OPERATOR" | "MANAGER"; status: "PENDING" | "ACTIVE" | "SUSPENDED"; first_seen_at: string; last_seen_at: string };
type Warehouse = { warehouseId: string; warehouseName: string; zone: string };
type PilotData = { groups: Group[]; members: Member[]; warehouseOptions: Warehouse[] };

export default function TelegramPilotAdminPage() {
  const [data, setData] = useState<PilotData>({ groups: [], members: [], warehouseOptions: [] });
  const [drafts, setDrafts] = useState<Record<string, Pick<Member, "warehouse_name" | "pilot_role" | "status">>>({});
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { setBusy(true); const response = await fetch("/api/admin/telegram-pilot", { cache: "no-store" }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.message || body.error || "Không thể tải Telegram pilot."); return; } setData({ groups: body.groups || [], members: body.members || [], warehouseOptions: body.warehouseOptions || [] }); setDrafts(Object.fromEntries((body.members || []).map((member: Member) => [member.id, { warehouse_name: member.warehouse_name, pilot_role: member.pilot_role, status: member.status }]))); };
  useEffect(() => { void load(); }, []);
  const groupNames = useMemo(() => new Map(data.groups.map((group) => [group.id, group.title || group.telegram_chat_id])), [data.groups]);
  const save = async (member: Member) => { const draft = drafts[member.id]; if (!draft?.warehouse_name) { setMessage("Chọn kho phụ trách trước khi kích hoạt thành viên."); return; } setBusy(true); const response = await fetch("/api/admin/telegram-pilot", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ memberId: member.id, warehouseName: draft.warehouse_name, pilotRole: draft.pilot_role, status: draft.status }) }); const body = await response.json(); setBusy(false); setMessage(response.ok ? `Đã lưu mapping cho ${member.display_name || "thành viên"}.` : body.message || body.error || "Lưu mapping thất bại."); if (response.ok) void load(); };
  const patch = (id: string, update: Partial<Pick<Member, "warehouse_name" | "pilot_role" | "status">>) => setDrafts((current) => ({ ...current, [id]: { ...(current[id] || { warehouse_name: null, pilot_role: "OPERATOR", status: "PENDING" }), ...update } }));
  return <main id="main-content" className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-teal-300">TG-01 · GROUP ENROLLMENT</p><h1 className="mt-1 flex items-center gap-3 text-3xl font-bold"><UsersRound/>Telegram Pilot</h1><p className="mt-2 max-w-3xl text-slate-400">Group chỉ dùng để giao tiếp và ghi nhận phản hồi. Chỉ manager trên OpsPilot mới kích hoạt người–kho; Telegram chưa thể đóng work order hoặc decision.</p></div><button type="button" onClick={() => void load()} disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-teal-800 px-4 font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-300"><RefreshCw aria-hidden="true" size={17}/>{busy ? "Đang xử lý…" : "Làm mới"}</button></header>
    {message && <p role="status" className="mt-5 rounded-lg border border-teal-700 bg-teal-950/40 p-3 text-sm">{message}</p>}
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-bold uppercase tracking-wide text-teal-300">1. Thêm bot vào group</p><p className="mt-2 text-sm text-slate-300">Bật webhook trước khi dùng. Bot chỉ nhận đăng ký từ group/supergroup.</p></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-bold uppercase tracking-wide text-teal-300">2. Nhân viên gõ /join</p><p className="mt-2 text-sm text-slate-300">Hệ thống ghi nhận Telegram ID; không đoán theo tên hoặc username.</p></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-bold uppercase tracking-wide text-teal-300">3. Manager mapping</p><p className="mt-2 text-sm text-slate-300">Chọn kho, vai trò và kích hoạt bên dưới. Chưa gửi work order thật ở TG-01.</p></article></section>
    <section className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold">Group đã nhận diện ({data.groups.length})</h2><div className="mt-3 space-y-2">{data.groups.length ? data.groups.map((group) => <div key={group.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-800 bg-slate-950/60 px-3 py-2 text-sm"><span className="font-semibold">{group.title || "Telegram group"}</span><span className="font-mono text-xs text-slate-400">chat {group.telegram_chat_id}</span></div>) : <p className="rounded-lg border border-dashed border-slate-700 p-4 text-sm text-slate-400">Chưa có group. Thêm bot, cấu hình webhook, rồi để một thành viên gõ <code>/join</code>.</p>}</div></section>
    <section className="mt-6"><div className="flex items-baseline justify-between gap-4"><h2 className="font-bold">Thành viên chờ mapping ({data.members.length})</h2><p className="text-xs text-slate-500">Tên Telegram chỉ để nhận diện; quyền dựa trên Telegram ID đã lưu.</p></div><div className="mt-3 space-y-3">{data.members.map((member) => { const draft = drafts[member.id] || { warehouse_name: member.warehouse_name, pilot_role: member.pilot_role, status: member.status }; return <article key={member.id} className="grid gap-4 rounded-xl border border-slate-800 bg-slate-900 p-4 lg:grid-cols-[minmax(190px,1.2fr)_minmax(260px,1.8fr)_150px_150px_auto] lg:items-end"><div><p className="font-semibold">{member.display_name || "Chưa có tên hiển thị"}</p><p className="mt-1 text-xs text-slate-500">{member.username ? `@${member.username} · ` : ""}{groupNames.get(member.group_id) || "Group chưa xác định"}</p><p className="mt-1 font-mono text-xs text-slate-600">Telegram ID: {member.telegram_user_id}</p></div><label className="text-sm font-medium">Kho phụ trách<select value={draft.warehouse_name || ""} onChange={(event) => patch(member.id, { warehouse_name: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-300"><option value="">Chọn kho từ danh mục…</option>{data.warehouseOptions.map((warehouse) => <option key={warehouse.warehouseId} value={warehouse.warehouseName}>{warehouse.warehouseName} · {warehouse.zone}</option>)}</select></label><label className="text-sm font-medium">Vai trò<select value={draft.pilot_role} onChange={(event) => patch(member.id, { pilot_role: event.target.value as Member["pilot_role"] })} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"><option value="OPERATOR">Nhân viên</option><option value="MANAGER">Manager</option></select></label><label className="text-sm font-medium">Trạng thái<select value={draft.status} onChange={(event) => patch(member.id, { status: event.target.value as Member["status"] })} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"><option value="PENDING">Chờ mapping</option><option value="ACTIVE">Kích hoạt</option><option value="SUSPENDED">Tạm dừng</option></select></label><button type="button" onClick={() => void save(member)} disabled={busy || !draft.warehouse_name} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#00a19a] px-4 font-bold text-black disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-300"><Save aria-hidden="true" size={17}/>Lưu</button></article>; })}{!data.members.length && <p className="rounded-xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400">Chưa có ai đăng ký. Sau khi webhook hoạt động, yêu cầu nhân viên gõ <code>/join</code> trong group.</p>}</div></section>
    <section className="mt-6 rounded-xl border border-amber-500/30 bg-amber-500/5 p-5"><h2 className="flex items-center gap-2 font-bold text-amber-100"><Send aria-hidden="true" size={18}/>Giới hạn phase hiện tại</h2><p className="mt-2 text-sm leading-6 text-amber-50/80">TG-01 chỉ ghi nhận đăng ký và phản hồi inbound có audit. Nút gửi work order, callback Nhận việc và nhắc SLA sẽ được bổ sung ở TG-02/TG-03 sau khi bạn test roster thành công.</p></section>
  </main>;
}
