"use client";
import { FormEvent, useState } from "react";
import { handleApiAccess } from "@/app/_components/apiAccess";
import { useOpsSession } from "@/app/_components/useOpsSession";
type Kind="verification"|"feedback"; type Status={type:"success"|"error";text:string}|null;
export function PilotFeedbackForms({incidentId}:{incidentId:string}){
 const session=useOpsSession();
 const[submitting,setSubmitting]=useState<Kind|null>(null),[verificationStatus,setVerificationStatus]=useState<Status>(null),[feedbackStatus,setFeedbackStatus]=useState<Status>(null);
 async function send(event:FormEvent<HTMLFormElement>,kind:Kind){event.preventDefault();const form=event.currentTarget,fields=new FormData(form),setStatus=kind==="verification"?setVerificationStatus:setFeedbackStatus;const body=kind==="verification"?{kind,actor:session.actor,actualCause:fields.get("actualCause"),evidence:fields.get("evidence"),notes:fields.get("notes")}:{kind,actor:session.actor,category:fields.get("category"),description:fields.get("description"),orderCodes:String(fields.get("orderCodes")||"").split(/[,\s]+/).filter(Boolean)};setSubmitting(kind);setStatus(null);try{const response=await fetch(`/api/incidents/${encodeURIComponent(incidentId)}/pilot-feedback`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();handleApiAccess(response,result,"Yêu cầu không thành công");form.reset();setStatus({type:"success",text:kind==="verification"?"Đã lưu xác minh bất biến.":"Đã gửi báo cáo vấn đề."})}catch(error:unknown){setStatus({type:"error",text:`Không thể lưu: ${error instanceof Error?error.message:String(error)}`})}finally{setSubmitting(null)}}
 const input="mt-1 min-h-11 w-full rounded border border-slate-700 bg-slate-950 px-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400",statusClass=(s:Status)=>s?.type==="error"?"border-rose-500/40 bg-rose-500/10 text-rose-100":"border-emerald-500/40 bg-emerald-500/10 text-emerald-100";
 return <section className="grid gap-4 xl:grid-cols-2" aria-label="Xác minh và phản hồi pilot"><form onSubmit={e=>void send(e,"verification")} className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-lg font-bold">Xác minh nguyên nhân thực tế</h2><p className="text-sm text-slate-400">Người xác minh: <strong className="text-blue-200">{session.actor||"Đang đọc phiên…"}</strong></p><label className="block">Nguyên nhân<select name="actualCause" className={input}><option value="UNKNOWN">Chưa xác định</option><option value="STAFFING">Nhân sự</option><option value="CAPACITY">Công suất/diện tích</option><option value="LINEHAUL">Xe trung chuyển</option><option value="PROCESS">Quy trình</option><option value="DATA_ERROR">Dữ liệu sai</option><option value="OTHER">Khác</option></select></label><label className="block">Bằng chứng<textarea required name="evidence" rows={3} className={input}/></label><label className="block">Ghi chú<textarea name="notes" rows={2} className={input}/></label><button type="submit" disabled={submitting==="verification"||session.loading||!session.can("VERIFY_INCIDENT")} className="min-h-11 rounded bg-emerald-600 px-4 font-semibold disabled:cursor-wait disabled:opacity-50">{submitting==="verification"?"Đang lưu…":"Lưu xác minh"}</button>{verificationStatus&&<p role={verificationStatus.type==="error"?"alert":"status"} aria-live="polite" className={`rounded-lg border p-3 text-sm ${statusClass(verificationStatus)}`}>{verificationStatus.text}</p>}</form><form onSubmit={e=>void send(e,"feedback")} className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-lg font-bold">Báo vấn đề</h2><p className="text-sm text-slate-400">Người báo: <strong className="text-blue-200">{session.actor||"Đang đọc phiên…"}</strong></p><label className="block">Loại vấn đề<select name="category" className={input}><option value="DATA">Dữ liệu</option><option value="SIGNAL">Nhãn tín hiệu</option><option value="AI">AI</option><option value="UI">Giao diện</option><option value="OTHER">Khác</option></select></label><label className="block">Mô tả<textarea required name="description" rows={3} className={input}/></label><label className="block">Mã đơn liên quan<input name="orderCodes" className={input}/></label><button type="submit" disabled={submitting==="feedback"||session.loading||!session.can("REPORT_FEEDBACK")} className="min-h-11 rounded bg-blue-600 px-4 font-semibold disabled:cursor-wait disabled:opacity-50">{submitting==="feedback"?"Đang gửi…":"Gửi báo cáo"}</button>{feedbackStatus&&<p role={feedbackStatus.type==="error"?"alert":"status"} aria-live="polite" className={`rounded-lg border p-3 text-sm ${statusClass(feedbackStatus)}`}>{feedbackStatus.text}</p>}</form></section>
}
