"use client";
import { useEffect, useState } from "react";
import { RefreshCw, Save, Upload, UsersRound } from "lucide-react";
type UserRow = { id: string; email?: string; role: string; employeeId: string | null; warehouseCount: number; zones: string[]; lastSignInAt?: string };
export default function AdminUsersPage() {
  const [users, setUsers] = useState<UserRow[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { setBusy(true); const response = await fetch("/api/admin/users", { cache: "no-store" }); const body = await response.json(); setBusy(false); response.ok ? setUsers(body.users || []) : setMessage(body.error || "Không thể tải người dùng"); };
  useEffect(() => { void load(); }, []);
  const update = async (user: UserRow) => { setBusy(true); const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId: user.id, role: user.role, employeeId: user.employeeId }) }); const body = await response.json(); setBusy(false); setMessage(response.ok ? `Đã cập nhật ${user.email}. Người dùng cần đăng nhập lại.` : body.error || "Cập nhật thất bại"); if (response.ok) void load(); };
  const preview = async (file: File) => { setBusy(true); const form = new FormData(); form.set("file", file); const response = await fetch("/api/admin/assignments/preview", { method: "POST", body: form }); const body = await response.json(); setBusy(false); setMessage(response.ok ? `Preview ${body.fileName}: ${body.summary.rows} kho; thêm ${body.summary.added}; bỏ ${body.summary.removed}; trùng ${body.summary.duplicates}; thiếu Manager ${body.summary.missingManager}. Chưa thay đổi production.` : body.error || "Không đọc được file"); };
  const setField = (id: string, patch: Partial<UserRow>) => setUsers((rows) => rows.map((row) => row.id === id ? { ...row, ...patch } : row));
  return <main id="main-content" className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-teal-300">Chỉ dành cho ADMIN</p><h1 className="mt-1 flex items-center gap-3 text-3xl font-bold"><UsersRound/>Quản trị người dùng</h1><p className="mt-2 text-slate-400">Gán vai trò và mã nhân viên; phạm vi được tính từ bảng phân công.</p></div><button onClick={() => void load()} disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-teal-800 px-4 font-semibold"><RefreshCw size={17}/>{busy ? "Đang xử lý…" : "Làm mới"}</button></header>{message && <p role="status" className="mt-5 rounded-lg border border-teal-700 bg-teal-950/40 p-3">{message}</p>}<section className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold">Kiểm tra bảng phân công mới</h2><p className="mt-1 text-sm text-slate-400">Upload Excel để xem diff và lỗi dữ liệu. Preview không ghi đè production.</p><label className="mt-4 inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-lg bg-slate-800 px-4 font-semibold"><Upload size={17}/>Chọn file Excel<input type="file" accept=".xlsx" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void preview(file); }}/></label></section><section className="mt-6 space-y-3">{users.map((user) => <article key={user.id} className="grid gap-4 rounded-xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-[minmax(180px,1.4fr)_160px_180px_1fr_auto] md:items-end"><div><p className="font-semibold">{user.email}</p><p className="mt-1 text-xs text-slate-500">Đăng nhập: {user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString("vi-VN") : "Chưa có"}</p></div><label className="text-sm">Vai trò<select value={user.role} onChange={(e) => setField(user.id, { role: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"><option>OPERATOR</option><option>REVIEWER</option><option>MANAGER</option><option>ADMIN</option></select></label><label className="text-sm">Mã nhân viên<input value={user.employeeId || ""} onChange={(e) => setField(user.id, { employeeId: e.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"/></label><div><p className="text-sm text-slate-400">{user.warehouseCount} kho</p><p className="mt-1 text-sm font-semibold text-teal-200">{user.zones.join(", ") || "Chưa có phạm vi"}</p></div><button onClick={() => void update(user)} disabled={busy || !user.employeeId} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#00a19a] px-4 font-bold text-black disabled:opacity-50"><Save size={17}/>Lưu</button></article>)}</section></main>;
}
