import Link from "next/link";

const card = "rounded-xl border border-slate-800 bg-slate-900 p-5";
const th = "border-b border-slate-700 p-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400";
const td = "border-b border-slate-800 p-3 align-top text-sm leading-6 text-slate-300";

export default function GuidePage() {
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <header><p className="text-sm font-semibold text-blue-300">Sổ tay vận hành OpsPilot</p><h1 className="mt-1 text-3xl font-bold">Hướng dẫn sử dụng và cách đọc số liệu</h1><p className="mt-3 max-w-4xl leading-7 text-slate-400">OpsPilot gom dữ liệu vận hành, phát hiện nhóm đơn bất thường, hỗ trợ phân tích và theo dõi kết quả. Nhãn sự cố và khuyến nghị AI là tín hiệu hỗ trợ; người vận hành phải đối chiếu mã đơn và dữ liệu kho trước khi hành động.</p></header>

    <nav aria-label="Mục lục hướng dẫn" className={`${card} flex flex-wrap gap-2`}>
      {[['#quy-trinh','Quy trình sử dụng'],['#nguon-du-lieu','Nguồn dữ liệu'],['#chi-so','Risk & ưu tiên'],['#incident','Trang sự cố'],['#ai','AI & duyệt'],['#followup','Theo dõi'],['#decision','Decision Inbox']].map(([href,label]) => <a key={href} href={href} className="rounded-lg border border-slate-700 px-3 py-2 text-sm font-semibold text-blue-200 hover:border-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-400">{label}</a>)}
    </nav>

    <section id="quy-trinh" className={card}><h2 className="text-xl font-bold">Quy trình sử dụng hằng ngày</h2><ol className="mt-4 grid gap-3 md:grid-cols-2"><li className="rounded-lg bg-slate-950 p-4"><strong>1. Điều hành:</strong> xem ô “Cần chú ý ngay”, ưu tiên sự cố rủi ro cao và các bản tổng hợp chờ phê duyệt.</li><li className="rounded-lg bg-slate-950 p-4"><strong>2. Sự cố:</strong> mở một sự cố, kiểm tra kho, tổng số đơn, tuổi đơn lâu nhất và các mã đơn mẫu.</li><li className="rounded-lg bg-slate-950 p-4"><strong>3. Bằng chứng:</strong> tra mã đơn trong hệ thống nguồn. Không coi nhãn như “Thiếu shipper” là nguyên nhân đã được chứng minh.</li><li className="rounded-lg bg-slate-950 p-4"><strong>4. Tổng hợp để duyệt:</strong> đọc bằng chứng, độ tin cậy, rủi ro và đề xuất; phê duyệt, sửa hoặc từ chối nếu dữ liệu khớp.</li><li className="rounded-lg bg-slate-950 p-4"><strong>5. Theo dõi kết quả:</strong> so số đơn hiện tại với mốc ban đầu; chỉ xác nhận hành động khi có bằng chứng thực thi.</li><li className="rounded-lg bg-slate-950 p-4"><strong>6. Hộp quyết định:</strong> dùng chế độ quan sát để lưu đề xuất và kết quả mà không tác động vận hành.</li></ol></section>

    <section id="nguon-du-lieu" className={card}><h2 className="text-xl font-bold">Các chỉ số lấy từ đâu?</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr><th className={th}>Thông tin</th><th className={th}>Nguồn</th><th className={th}>Cách hiểu</th></tr></thead><tbody>
      <tr><td className={td}>Kho, nhãn sự cố, số đơn, tuổi đơn</td><td className={td}>Snapshot đơn hàng nguồn → bảng sự cố và bản ghi lịch sử sự cố mới nhất</td><td className={td}>Số đơn là toàn bộ đơn khớp rule ở thời điểm snapshot, không phải số mã đang hiện trên màn hình.</td></tr>
      <tr><td className={td}>Mã đơn để kiểm tra</td><td className={td}>Danh sách mã mẫu lưu trong snapshot lịch sử</td><td className={td}>UI hiện tối đa 5 mã để kiểm tra nhanh. Ví dụ “5/51” nghĩa là 5 mã mẫu trên tổng 51 đơn, không phải chỉ có 5 đơn.</td></tr>
      <tr><td className={td}>Root Cause, Planner, Copilot</td><td className={td}>Kết quả run đã lưu của từng agent, gắn với incident/snapshot</td><td className={td}>Có thể cũ hơn snapshot hiện tại. Cảnh báo dữ liệu cũ phải được xử lý trước khi duyệt.</td></tr>
      <tr><td className={td}>Follow-up</td><td className={td}>Case và sự kiện follow-up đã lưu</td><td className={td}>So sánh số đơn hiện tại với baseline tại lúc bắt đầu theo dõi.</td></tr>
      <tr><td className={td}>Sức khỏe hệ thống/AI</td><td className={td}>API health, kết nối database và cấu hình dịch vụ AI</td><td className={td}>Cho biết hệ thống có sẵn sàng xử lý, không chứng minh một kết luận AI là đúng.</td></tr>
      <tr><td className={td}>Decision/outcome</td><td className={td}>Decision Core: decision, evidence snapshot, audit event và outcome</td><td className={td}>Financial impact luôn “Chưa đánh giá”; hệ thống không tính saving.</td></tr>
    </tbody></table></div></section>

    <section id="chi-so" className={card}><h2 className="text-xl font-bold">Cơ sở tính Mức ưu tiên và Rủi ro</h2><div className="mt-4 grid gap-4 xl:grid-cols-2">
      <article className="rounded-lg bg-slate-950 p-4"><h3 className="font-bold text-amber-300">Mức ưu tiên (Priority)</h3><p className="mt-2 text-sm leading-6 text-slate-300"><code>(min(số đơn × 2, 100) + min(tuổi lớn nhất × 0,5, 50)) × trọng số loại sự cố</code>, làm tròn một chữ số.</p><p className="mt-2 text-sm text-slate-400">Trọng số: Kho tồn 1,5; Kho chưa lấy 1,3; Thiếu shipper 1,2; Kho chưa luân chuyển 1,0. High từ 50; Critical từ 75. Priority dùng để xếp thứ tự xử lý, không phải phần trăm và không phải độ tin cậy AI.</p></article>
      <article className="rounded-lg bg-slate-950 p-4"><h3 className="font-bold text-rose-300">Điểm rủi ro (Risk)</h3><p className="mt-2 text-sm leading-6 text-slate-300">Tổng điểm xác định từ bốn nhóm: số đơn (0/5/10/20/30), tuổi đơn lâu nhất (0/10/20/30), xu hướng (0–30), thời gian sự cố kéo dài (0/5/10/20), giới hạn tối đa 100.</p><p className="mt-2 text-sm text-slate-400">Low dưới 25; Medium 25–49; High 50–74; Critical từ 75. Risk đo mức phơi nhiễm vận hành hiện tại, khác với Priority là thứ tự cần xem.</p></article>
    </div><div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100"><strong>Khi High/Critical:</strong> kiểm tra snapshot và mã đơn ngay, xác minh nhãn rule bằng dữ liệu kho, xem xu hướng/tuổi đơn, rồi chuyển đúng người phụ trách. Critical cần được chú ý trước. OpsPilot không tự thực thi hành động vận hành.</div></section>

    <section id="incident" className={card}><h2 className="text-xl font-bold">Cách đọc trang Sự cố</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr><th className={th}>Mục</th><th className={th}>Ý nghĩa</th><th className={th}>Cần kiểm tra</th></tr></thead><tbody><tr><td className={td}>Đơn ảnh hưởng</td><td className={td}>Tổng đơn khớp rule trong snapshot mới nhất.</td><td className={td}>Đối chiếu timestamp và mã mẫu; không nhầm với số mã UI hiển thị.</td></tr><tr><td className={td}>Tuổi lớn nhất</td><td className={td}>Số giờ của đơn tồn lâu nhất trong nhóm.</td><td className={td}>Mã của đơn lâu nhất được hiển thị nếu nguồn có cung cấp; nếu không, kiểm tra các mã mẫu ở hệ thống nguồn.</td></tr><tr><td className={td}>Nhãn “Thiếu shipper/Kho tồn…”</td><td className={td}>Nhãn tín hiệu do rule phát hiện, dùng để phân nhóm.</td><td className={td}>Không phải kết luận nguyên nhân. Cần kiểm tra phân công, scan, trạng thái giao và ca kho.</td></tr><tr><td className={td}>Độ tin cậy</td><td className={td}>Mức tự tin của phân tích AI trên dữ liệu đầu vào.</td><td className={td}>Không thay thế bằng chứng và không phải xác suất hành động thành công.</td></tr></tbody></table></div></section>

    <section id="ai" className={card}><h2 className="text-xl font-bold">Đề xuất xử lý và tổng hợp để duyệt</h2><p className="mt-3 leading-7 text-slate-300"><strong>Đề xuất xử lý</strong> nêu việc nên kiểm tra hoặc thực hiện. <strong>Tổng hợp để duyệt</strong> gom nguyên nhân, bằng chứng, rủi ro và đề xuất để con người quyết định. Phê duyệt xác nhận nội dung, chỉnh sửa lưu bản người vận hành sửa, còn từ chối bắt buộc nêu lý do. Các nút này không tự thực hiện tác vụ vận hành. Nếu số đơn trong bản tổng hợp khác dữ liệu mới nhất, hãy tạo lại phân tích hoặc từ chối kết quả cũ.</p></section>

    <section id="followup" className={card}><h2 className="text-xl font-bold">Cách đọc trang Theo dõi</h2><p className="mt-3 leading-7 text-slate-300">Mỗi thẻ là một case theo dõi cho một kho + loại sự cố. “Mốc ban đầu” là số đơn lúc tạo case; “Hiện tại” là số đơn ở lần đọc gần nhất. Cải thiện = <code>(mốc ban đầu − hiện tại) / mốc ban đầu × 100%</code>. Vì vậy +100% nghĩa là số đơn đã giảm về 0; số âm nghĩa là tình hình xấu đi.</p><ul className="mt-4 grid gap-3 md:grid-cols-2"><li className="rounded-lg bg-slate-950 p-4"><strong>Chờ lần nhắc đầu/tiếp theo:</strong> hệ thống đang đợi mốc follow-up kế tiếp.</li><li className="rounded-lg bg-slate-950 p-4"><strong>Chờ phản hồi:</strong> đã yêu cầu cập nhật nhưng chưa có xác nhận.</li><li className="rounded-lg bg-slate-950 p-4"><strong>Đã xử lý:</strong> điều kiện dữ liệu cho thấy incident đã về ngưỡng giải quyết.</li><li className="rounded-lg bg-slate-950 p-4"><strong>Xác nhận thực thi:</strong> chỉ bấm khi có bằng chứng hành động thực tế; nút này ghi audit, không tự thực thi.</li></ul><Link href="/followups" className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-blue-600 px-4 text-sm font-semibold hover:bg-blue-500">Mở trang Theo dõi</Link></section>

    <section id="decision" className={card}><h2 className="text-xl font-bold">Decision Inbox</h2><p className="mt-3 leading-7 text-slate-300"><strong>SHADOW</strong> lưu recommendation và evidence để so với outcome thực tế, chỉ đọc và không tác động operation. <strong>HUMAN_APPROVAL</strong> cho phép người có actor hợp lệ approve/reject nhưng vẫn không tự execute. <strong>AUTONOMOUS</strong> bị chặn tại runtime/API. Inbox trống thì chọn incident đã kiểm tra và tạo SHADOW; sau thời gian đo, ghi SUCCESS, FAILURE hoặc INCONCLUSIVE kèm bằng chứng. Không có phép tính saving.</p><Link href="/decisions" className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-indigo-600 px-4 text-sm font-semibold hover:bg-indigo-500">Mở Decision Inbox</Link></section>
  </main>;
}
