// src/observability/errorCodes.ts
export enum ErrorCode {
  UNKNOWN = 'UNKNOWN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  DB_ERROR = 'DB_ERROR',
  PROJECTION_REFRESH_FAILED = 'PROJECTION_REFRESH_FAILED',
  AI_JOB_PROCESSING_FAILED = 'AI_JOB_PROCESSING_FAILED',
  AI_WORKFLOW_FAILED = 'AI_WORKFLOW_FAILED',
}
