import { describe, expect, it } from "vitest";
import { CAPACITY_ACTIONS, acceptLeadFact, allowedActions, buildContext, critique, detectCandidate, executionInstruction, factRequestNeeded, precheck, verifyCapacityOutcome, type AiRecommendation, type CurrentRisk, type LeadFact } from "@/domain/near-term-capacity";
import { buildNearTermFactCallbackData, formatNearTermFactRequest, formatNearTermManagerCard, parseNearTermFactCallbackData } from "@/integrations/telegram/near-term-capacity-message";
import { parseLeadDetail } from "@/services/near-term-capacity-runtime";
import fs from "node:fs";

const now = new Date();
const facts: CurrentRisk = { warehouseId: "WH-1", warehouseName: "Kho 1", capturedAt: now.toISOString(), currentOrders: 12, currentKg: 500, b2bOrders: 3, evidenceRefs: ["incident:1", "checkpoint:1"], riskSignals: ["PERSISTED_SLA_RISK"], hardSlaConstraint: "B2B due today" };
const policy = { nearTermWindowMinutes: 240, leadFactMaxAgeMinutes: 60, allowedActions: CAPACITY_ACTIONS } as const;
const lead: LeadFact = { interactionId: "telegram:1", suppliedBy: "lead:1", capturedAt: now.toISOString(), source: "HUMAN_OPERATIONAL_GROUND_TRUTH", incoming: "CONFIRMED_ETA", expectedIncomingKg: 200, expectedIncomingAt: new Date(now.getTime() + 60_000).toISOString(), incomingType: "MIXED", availableVehicles: 1, availableManpower: 0, confidence: "HIGH" };
function recommendation(overrides: Partial<AiRecommendation> = {}): AiRecommendation { return { decision_case_id: "case-1", recommended_action: "ADD_VEHICLE", confidence: .8, reason_summary: "risk", current_risk: "risk", expected_state_if_no_action: "breach", expected_state_if_action: "reduce", key_evidence: ["incident:1"], uncertainties: [], execution_instruction: "Arrange one verified vehicle", required_by: new Date(now.getTime() + 10_000).toISOString(), required_followup_at: new Date(now.getTime() + 20_000).toISOString(), estimated_cost_vnd: null, estimated_saving_vnd: null, ...overrides }; }

describe("near-term capacity decision loop", () => {
  it("keeps every Phase 2 persistence table server-only with RLS and no client policy", () => { const sql = fs.readFileSync("src/database/migrations/067_near_term_capacity_decision_loop.sql", "utf8"); for (const table of ["near_term_capacity_cases", "near_term_capacity_fact_responses", "near_term_capacity_events"]) expect(sql).toContain(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;`); expect(sql).not.toMatch(/CREATE\s+POLICY|USING\s*\(\s*true\s*\)|WITH\s+CHECK\s*\(\s*true\s*\)/i); });
  it("detects only evidenced candidates and requests Lead facts", () => { expect(detectCandidate(facts)).toBe(true); expect(factRequestNeeded(facts)).toBe(true); expect(detectCandidate({ ...facts, riskSignals: [] })).toBe(false); });
  it("persists the first Lead fact only", () => { const first = acceptLeadFact(null, lead); expect(acceptLeadFact(first, { ...lead, incoming: "UNKNOWN" })).toBe(first); });
  it("routes missing or invalid facts to investigation", () => { expect(precheck(facts, null, policy)).toContain("LEAD_FACT_MISSING"); expect(allowedActions(facts, null, policy)).toEqual(["HUMAN_INVESTIGATION_REQUIRED"]); });
  it("builds a bounded context and accepts one valid AI decision", () => { const context = buildContext("case-1", facts, lead, policy); expect(context.allowedActions).toContain("ADD_VEHICLE"); expect(critique(context, recommendation())).toEqual({ verdict: "VALID_DECISION", reasons: [] }); });
  it("blocks unsupported actions, finance fabrication, and conflicting critic output", () => { const context = buildContext("case-1", facts, lead, policy); expect(critique(context, recommendation({ recommended_action: "ADD_VEHICLE" as any, key_evidence: ["fake"], estimated_cost_vnd: 1 }))).toMatchObject({ verdict: "HUMAN_INVESTIGATION_REQUIRED", reasons: expect.arrayContaining(["UNVERIFIED_EVIDENCE_REFERENCE", "UNSUPPORTED_FINANCIAL_VALUE"]) }); expect(critique(context, recommendation({ recommended_action: "INVENT_ACTION" as any })).reasons).toContain("ACTION_NOT_ALLOWED"); });
  it("does not expose reallocation without an actually available resource", () => { expect(allowedActions(facts, { ...lead, availableVehicles: 0, availableManpower: 0 }, policy)).not.toContain("REALLOCATE_AVAILABLE_CAPACITY"); });
  it("creates only executable Phase 1 instructions", () => { expect(executionInstruction("ADD_MANPOWER", "Prepare two confirmed sorters")).toMatch(/two/); expect(() => executionInstruction("NO_ACTION_MONITOR", "x")).toThrow("NON_EXECUTABLE_ACTION"); });
  it("verifies success, failure, and inconclusive without inventing money", () => { expect(verifyCapacityOutcome({ actionExecuted: "YES", slaOutcome: "PRESERVED", riskAfterAction: "REDUCED" })).toBe("SUCCESS"); expect(verifyCapacityOutcome({ actionExecuted: "NO", slaOutcome: "UNKNOWN", riskAfterAction: "UNKNOWN" })).toBe("FAILURE"); expect(verifyCapacityOutcome({ actionExecuted: "UNKNOWN", slaOutcome: "UNKNOWN", riskAfterAction: "UNKNOWN" })).toBe("INCONCLUSIVE"); });
  it("keeps Telegram Lead interaction factual and the Manager card single-action with guarded finance", () => { const factText = formatNearTermFactRequest(facts, 240); expect(factText).toContain("CẦN XÁC NHẬN"); expect(factText).not.toMatch(/nên làm gì/i); const card = formatNearTermManagerCard(facts.warehouseName, recommendation()); expect(card).toContain("ADD_VEHICLE"); expect(card).toContain("Chưa đủ dữ liệu xác minh chi phí"); expect(card).not.toContain("HOLD_LOW_PRIORITY_ECOM"); });
  it("uses a bounded callback namespace and accepts only complete Lead detail facts", () => { const id = "123e4567-e89b-42d3-a456-426614174000"; const callback = buildNearTermFactCallbackData(id, "CONFIRMED_ETA"); expect(parseNearTermFactCallbackData(callback)).toEqual({ caseId: id, answer: "CONFIRMED_ETA" }); expect(parseNearTermFactCallbackData("opspcap:bad:ADD_VEHICLE")).toBeNull(); expect(parseLeadDetail("KG=125.5; ETA=2026-09-10T10:00:00.000Z; TYPE=MIXED")).toMatchObject({ expectedIncomingKg: 125.5, incomingType: "MIXED" }); expect(parseLeadDetail("KG=125; TYPE=ECOM")).toBeNull(); });
});
