// src/workflow/WorkflowState.ts
export enum WorkflowState {
  NEW = "NEW",
  ROOTCAUSE_RUNNING = "ROOTCAUSE_RUNNING",
  ROOTCAUSE_COMPLETED = "ROOTCAUSE_COMPLETED",
  PLANNER_RUNNING = "PLANNER_RUNNING",
  PLANNER_COMPLETED = "PLANNER_COMPLETED",
  COPILOT_RUNNING = "COPILOT_RUNNING",
  COPILOT_COMPLETED = "COPILOT_COMPLETED",
  COPILOT_AWAITING_REVIEW = "COPILOT_AWAITING_REVIEW",
  COPILOT_REVIEW_APPROVED = "COPILOT_REVIEW_APPROVED",
  COPILOT_REVIEW_EDITED = "COPILOT_REVIEW_EDITED",
  COPILOT_REVIEW_REJECTED = "COPILOT_REVIEW_REJECTED",
  FOLLOWUP_RUNNING = "FOLLOWUP_RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

