"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, ClipboardCheck, RefreshCw } from "lucide-react";
import { repairOperationalText, translateStatus } from "@/app/_components/operationalText";
import { handleApiAccess } from "@/app/_components/apiAccess";

interface QueueItem { incidentId:string; runId:string; status:"PENDING"|"APPROVED"|"EDITED"|"REJECTED"|"SUPERSEDED"; confidence?:number; risk?:string; title?:string; warehouseId?:string; zoneName?:string|null; warehouseName?:string; reasonName?:string; affectedOrderCount?:number; sampleOrderCodes?:string[]; oldestOrderCode?:string|null; createdAt:string; }

export default function ReviewQueuePage() {
  const [items,setItems]=useState<QueueItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{ setLoading(true); setError(""); try { const response=await fetch("/api/copilot/reviews?limit=100",{cache:"no-store"}); const payload=await response.json(); handleApiAccess(response,payload,"Không thể tải hàng đợi duyệt."); if(!payload.ok) throw new Error(payload.message||"Không thể tải hàng đợi duyệt."); setItems((payload.items||[]).filter((item:QueueItem)=>item.status==="PENDING").sort((a:QueueItem,b:QueueItem)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())); } catch(caught){setError(caught instanceof Error?caught.message:String(caught));} finally{setLoading(false);} },[]);
  useEffect(()=>{void load();},[load]);
  const pendingCount=items.length;
  return <main id="main-content" tabIndex={-1} className="min-h-dvh bg-slate-950 px-4 py-6 text-slate-100 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-5">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-300">AI đã phân tích · chờ con người quyết định</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Cần phê duyệt</h1><p className="mt-1 text-sm text-slate-400">{pendingCount} bản phân tích đang chờ kiểm tra trong phạm vi đã chọn.</p><p className="mt-2 text-sm font-semibold text-cyan-200">Việc cần làm: mở từng bản, đối chiếu bằng chứng rồi Phê duyệt, Chỉnh sửa hoặc Từ chối.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-700 px-4 text-sm font-semibold hover:bg-slate-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400 disabled:opacity-50"><RefreshCw aria-hidden="true" size={17} className={loading?"animate-spin motion-reduce:animate-none":""}/>Làm mới</button></header>
    <div aria-live="polite">{loading&&<p className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-400">Đang tải các bản tổng hợp…</p>}{error&&<div role="alert" className="rounded-xl border border-rose-500/40 bg-rose-500/10 p-4 text-rose-200"><p className="font-semibold">Không tải được hàng đợi phê duyệt</p><p className="mt-1 text-sm">{error}</p></div>}{!loading&&!error&&items.length===0&&<p className="rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-400">Không có sự cố nào đang cần phê duyệt trong phạm vi của bạn.</p>}</div>
    <section aria-label="Hàng đợi duyệt Copilot" className="grid gap-3">{items.map(item=>{const title=item.warehouseName?`${repairOperationalText(item.reasonName||"Sự cố")} · ${repairOperationalText(item.warehouseName)}`:repairOperationalText(item.title||"Sự cố cần phê duyệt"); return <Link key={item.runId} href={`/copilot/${encodeURIComponent(item.incidentId)}`} className="group rounded-xl border border-slate-800 bg-slate-900 p-4 transition-colors hover:border-blue-500/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full border border-amber-500/40 bg-amber-500/10 px-2.5 py-1 text-amber-200"><ClipboardCheck aria-hidden="true" className="mr-1 inline" size={13}/>{translateStatus(item.status)}</span>{item.zoneName&&<span className="rounded-full border border-cyan-500/40 px-2.5 py-1 text-cyan-200">{item.zoneName}</span>}</div><h2 className="mt-3 break-words text-lg font-bold">{title}</h2><p className="mt-2 text-sm text-slate-300"><strong>Số đơn tồn đọng: {item.affectedOrderCount??"Chưa có dữ liệu"}</strong></p></div><ArrowRight aria-hidden="true" size={20} className="shrink-0 text-blue-300"/></div></Link>;})}</section>
  </div></main>;
}
