"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, ClipboardCheck, RefreshCw } from "lucide-react";
import { repairOperationalText, translateStatus } from "@/app/_components/operationalText";
import { handleApiAccess } from "@/app/_components/apiAccess";

interface QueueItem { incidentId:string; runId:string; status:"PENDING"|"APPROVED"|"EDITED"|"REJECTED"; confidence?:number; risk?:string; title?:string; warehouseId?:string; zoneName?:string|null; warehouseName?:string; reasonName?:string; affectedOrderCount?:number; sampleOrderCodes?:string[]; oldestOrderCode?:string|null; createdAt:string; }
const PREFERRED_ZONE = "Miền Bắc 3";

export default function ReviewQueuePage() {
  const [items,setItems]=useState<QueueItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [zoneFilter,setZoneFilter]=useState(PREFERRED_ZONE);
  const load=useCallback(async()=>{ setLoading(true); setError(""); try { const response=await fetch("/api/copilot/reviews?limit=100",{cache:"no-store"}); const payload=await response.json(); handleApiAccess(response,payload,"Không thể tải hàng đợi duyệt."); if(!payload.ok) throw new Error(payload.message||"Không thể tải hàng đợi duyệt."); setItems((payload.items||[]).sort((a:QueueItem,b:QueueItem)=>(a.zoneName===PREFERRED_ZONE?-1:1)-(b.zoneName===PREFERRED_ZONE?-1:1)||(a.status==="PENDING"?-1:1)-(b.status==="PENDING"?-1:1)||new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())); } catch(caught){setError(caught instanceof Error?caught.message:String(caught));} finally{setLoading(false);} },[]);
  useEffect(()=>{void load();},[load]);
  const zones=useMemo(()=>[...new Set(items.map(item=>item.zoneName).filter((zone):zone is string=>Boolean(zone)))].sort((a,b)=>a.localeCompare(b,"vi")),[items]);
  const visibleItems=useMemo(()=>zoneFilter==="ALL"?items:items.filter(item=>item.zoneName===zoneFilter),[items,zoneFilter]);
  const pendingCount=visibleItems.filter(item=>item.status==="PENDING").length;
  return <main id="main-content" tabIndex={-1} className="min-h-dvh bg-slate-950 px-4 py-6 text-slate-100 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-5">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-300">AI đã phân tích · chờ con người quyết định</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Cần phê duyệt</h1><p className="mt-1 text-sm text-slate-400">{pendingCount} bản phân tích đang chờ kiểm tra trong phạm vi đã chọn.</p><p className="mt-2 text-sm font-semibold text-cyan-200">Việc cần làm: mở từng bản, đối chiếu bằng chứng rồi Phê duyệt, Chỉnh sửa hoặc Từ chối.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-700 px-4 text-sm font-semibold hover:bg-slate-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400 disabled:opacity-50"><RefreshCw aria-hidden="true" size={17} className={loading?"animate-spin motion-reduce:animate-none":""}/>Làm mới</button></header>
    {!loading&&!error&&<section aria-label="Bộ lọc hàng đợi duyệt" className="flex items-end justify-between rounded-xl border border-slate-800 bg-slate-900 p-4"><div><h2 className="font-semibold">Phạm vi phê duyệt</h2><p className="mt-1 text-sm text-slate-400">Mặc định tập trung các kho thuộc Miền Bắc 3.</p></div><label className="grid gap-1 text-sm font-semibold">Vùng<select value={zoneFilter} onChange={event=>setZoneFilter(event.target.value)} className="min-h-11 min-w-52 rounded-lg border border-slate-700 bg-slate-950 px-3"><option value="ALL">Tất cả vùng ({items.length})</option>{zones.map(zone=><option key={zone} value={zone}>{zone} ({items.filter(item=>item.zoneName===zone).length})</option>)}</select></label></section>}
    <div aria-live="polite">{loading&&<p className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-400">Đang tải các bản tổng hợp…</p>}{error&&<div role="alert" className="rounded-xl border border-rose-500/40 bg-rose-500/10 p-4 text-rose-200"><p className="font-semibold">Không tải được hàng đợi phê duyệt</p><p className="mt-1 text-sm">{error}</p></div>}{!loading&&!error&&visibleItems.length===0&&<p className="rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-400">Không có bản tổng hợp nào trong vùng đã chọn.</p>}</div>
    <section aria-label="Hàng đợi duyệt Copilot" className="grid gap-3">{visibleItems.map(item=>{const checkCode=item.oldestOrderCode||item.sampleOrderCodes?.[0]; const title=item.warehouseName?`${repairOperationalText(item.reasonName||"Sự cố")} · ${repairOperationalText(item.warehouseName)}`:repairOperationalText(item.title||item.incidentId); return <Link key={item.runId} href={`/copilot/${encodeURIComponent(item.incidentId)}`} className="group rounded-xl border border-slate-800 bg-slate-900 p-4 transition-colors hover:border-blue-500/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className={`rounded-full border px-2.5 py-1 ${item.status==="PENDING"?"border-amber-500/40 bg-amber-500/10 text-amber-200":"border-slate-700 text-slate-300"}`}><ClipboardCheck aria-hidden="true" className="mr-1 inline" size={13}/>{translateStatus(item.status)}</span><span className="rounded-full border border-slate-700 px-2.5 py-1">Rủi ro: {translateStatus(item.risk||"—")}</span>{item.zoneName&&<span className="rounded-full border border-cyan-500/40 px-2.5 py-1 text-cyan-200">{item.zoneName}</span>}</div><h2 className="mt-3 break-words text-lg font-bold">{title}</h2><p className="mt-2 text-sm text-slate-300"><strong>{item.affectedOrderCount??"—"} đơn ảnh hưởng</strong>{checkCode?` · Mã kiểm tra: ${checkCode}`:" · Chưa có mã đơn mẫu"}</p><p className="mt-1 break-all text-xs text-slate-500">Mã incident: {item.incidentId} · Độ tin cậy: {item.confidence??"—"}%</p></div><ArrowRight aria-hidden="true" size={20} className="shrink-0 text-blue-300"/></div></Link>;})}</section>
  </div></main>;
}
